version: "3.9"
services:
  # Run FastAPI with auto-reload and mount code
  api:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./api/app:/app/app:rw

  # Run ingest with auto-restart on file changes using watchfiles
  ingest:
    command: ["sh", "-lc", "pip install -q watchfiles && python -m watchfiles 'python -m src.main' /app/src"]
    volumes:
      - ./ingest/src:/app/src:rw

  # Keep production web image off in dev runs
  web:
    profiles: ["prod"]

  # Angular dev server with hot reload
  web-dev:
    image: node:20
    working_dir: /app
    command: ["npm", "start"]
    environment:
      - TZ=${TZ:-America/New_York}
      - CHOKIDAR_USEPOLLING=true
    ports: ["4200:4200"]
    volumes:
      - ./web-angular:/app:rw
    depends_on: [api]
    profiles: ["dev"]
