[project]
name = "bmore-transit-ingest"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "protobuf>=5.27.0",
  "gtfs-realtime-bindings>=0.0.7",
  "redis>=5.0.0",
  "psycopg2-binary>=2.9.9",
  "python-dotenv>=1.0.0",
  "requests>=2.32.0",
  "prometheus-client>=0.20.0",
]
